(defun soucin (lst1 lst2)
	(if (eq lst1 nil)
	  (if  (eq lst2 nil)
		nil
		(cons  (car lst2) (soucin lst1 (cdr lst2)))
	  )
          (if (eq lst2 nil)
	    (cons (car lst1) (soucin (cdr lst1) lst2))
	    (if (listp (car lst1))
		(cons (soucin (car lst1) (car lst2)) (soucin (cdr lst1) (cdr lst2)))
	        (cons (* (car lst1) (car lst2)) (soucin (cdr lst1) (cdr lst2)))
	    )
	   )
	) 
)
